grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: provider-site
        orgId: 1
        folder: ''
        type: file
        disableDeletion: true
        editable: false
        options:
          path: /var/lib/grafana/dashboards/provider-site
  dashboards:
    provider-site:
      MySQL-Dashboard:
        gnetId: 7362
        revision: 5
        datasource: Prometheus
      ApacheDash:
        gnetId: 3894
        revision: 7
        datasource: Prometheus
