---

  - name: Install python deps
    pip:
      name: passlib 

  - name: Gen htpasswd
    htpasswd:
      path: /home/k3s/passwd
      name: "{{ kibana_username }}"
      password: "{{ kibana_password }}"

  - name: Create efk namespace
    kubernetes.core.k8s:
      name: "{{ efk_namespace }}"
      api_version: v1
      kind: Namespace
      state: present

  - name: Create secret for kibana
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Secret
        type: Opaque
        metadata:
          name: kibana-secret
          namespace: "{{ efk_namespace }}"
        data:
          auth: "{{ lookup('file', '/home/k3s/passwd') | b64encode }}" 

  - name: Apply elasticsearch manifests
    kubernetes.core.k8s:
      state: present
      namespace: "{{ efk_namespace }}" 
      definition: "{{ lookup('template', 'kubernetes-efk/es.yaml.j2') | from_yaml_all }}"

  - name: Apply Fluentd manifests
    kubernetes.core.k8s:
      state: present
      namespace: "{{ efk_namespace }}"
      definition: "{{ lookup('template', 'kubernetes-efk/fluentd.yaml.j2') | from_yaml_all }}"

  - name: Apply Kibana manifests
    kubernetes.core.k8s:
      state: present
      namespace: "{{ efk_namespace }}"
      definition: "{{ lookup('template', 'kubernetes-efk/kibana.yaml.j2') | from_yaml_all }}"

