---

  - name: Pull mariadb_pass
    command: "kubectl get secret -o jsonpath={.data.mariadb-root-password} {{ wordpress_name }}-mariadb"
    register: mariadb_pass_raw

  - name: Setting fact with pwds
    set_fact:
      mariadb_pass: "{{ mariadb_pass_raw.stdout | b64decode }}"
      exporter_pass: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
      
  - name: Add helm repo
    kubernetes.core.helm_repository:
      name: prometheus-community
      repo_url: https://prometheus-community.github.io/helm-charts

  - name: Transfer grafana values
    template:
      src: "{{ role_path }}/templates/grafana/values.yaml.j2"
      dest: /home/k3s/grafana_values.yaml

  - name: Transfer alertmanager values
    template:
      src: "{{ role_path }}/templates/alertmanager/values.yaml.j2"
      dest: /home/k3s/alertmanager_values.yaml

  - name: Deploy Prometheus Operator with helm
    kubernetes.core.helm:
      name: "{{ prometheusOperator_name }}"
      chart_ref: prometheus-community/kube-prometheus-stack
      update_repo_cache: true
      release_namespace: "{{ prometheusOperator_namespace }}"
      create_namespace: true
      values_files:
      -  /home/k3s/grafana_values.yaml
      -  /home/k3s/alertmanager_values.yaml

  - name: Delete old user if exists
    kubernetes.core.k8s_exec:
      namespace: "{{ wordpress_namespace }}"
      pod: "{{ wordpress_name }}-mariadb-0"
      command: mariadb -uroot -p"{{ mariadb_pass }}" -e "DROP USER mysqld_exporter;"
    ignore_errors: true

  - name: Create user for mysql exporter
    kubernetes.core.k8s_exec:
      namespace: "{{ wordpress_namespace }}"
      pod: "{{ wordpress_name }}-mariadb-0"
      command: mariadb -uroot -p"{{ mariadb_pass }}" -e "CREATE USER 'mysqld_exporter' IDENTIFIED BY '"{{ exporter_pass }}"' WITH MAX_USER_CONNECTIONS 3;"

  - name: Grant privileges for mysql exporter
    kubernetes.core.k8s_exec:
      namespace: "{{ wordpress_namespace }}"
      pod: "{{ wordpress_name }}-mariadb-0"
      command: 
        mysql -uroot -p"{{ mariadb_pass }}" -e "GRANT PROCESS, REPLICATION CLIENT, REPLICATION SLAVE, SELECT ON *.* TO 'mysqld_exporter';"
        mysql -uroot -p"{{ mariadb_pass }}" -e "flush privileges;"

  - name: Deploy mysqld_exporter
    kubernetes.core.k8s:
      state: present
      namespace: "{{ wordpress_namespace }}"
      definition: "{{ lookup('template', 'mysqld_exporter.yaml.j2') | from_yaml }}"

  - name: Service for mysqld_exporter
    kubernetes.core.k8s:
      state: present
      namespace: "{{ wordpress_namespace }}"
      definition: "{{ lookup('file', 'mysqld_exporter_service.yaml') | from_yaml }}"
                
  - name: Create ServiceMonitor
    kubernetes.core.k8s:
      state: present
      namespace: "{{ wordpress_namespace }}"
      definition: "{{ lookup('template', 'ServiceMonitorMysql.yaml.j2') | from_yaml }}"

  - name: Create ServiceMonitor for apache exporter
    kubernetes.core.k8s:
      state: present
      namespace: "{{ wordpress_namespace }}"
      definition: "{{ lookup('template', 'ServiceMonitorWordpress.yaml.j2') | from_yaml }}"
    
  - name: Patch wordpress metric service
    kubernetes.core.k8s_json_patch:
      kind: Service
      namespace: "{{ wordpress_namespace }}"
      name: "{{ wordpress_name }}-wordpress-metrics"
      patch:
        - op: add
          path: /metadata/labels/exporter
          value: apache

  - name: Load rules for database
    kubernetes.core.k8s:
      state: present
      namespace: "{{ prometheusOperator_namespace }}"
      definition:
        apiVersion: monitoring.coreos.com/v1
        kind: PrometheusRule
        metadata:
          creationTimestamp: null
          labels:
            role: alert-rules
            release: "{{ prometheusOperator_name }}"
          name: prometheus-mysql-rules
        spec:
          "{{ lookup('file', 'alerts/mysqld-exporter.yml') | from_yaml }}"

  - name: Load rules for apache
    kubernetes.core.k8s:
      state: present
      namespace: "{{ prometheusOperator_namespace }}"
      definition:
        apiVersion: monitoring.coreos.com/v1
        kind: PrometheusRule
        metadata:
          creationTimestamp: null
          labels:
            role: alert-rules
            release: "{{ prometheusOperator_name }}"
          name: prometheus-apache-rules
        spec:
          "{{ lookup('file', 'alerts/apache-exporter.yml') | from_yaml }}"

  - name: include efk stack
    include_tasks:
      file: efk-setup.yaml
