---

  - name: Pull mariadb_pass
    command: "kubectl get secret -o jsonpath={.data.mariadb-root-password} cms-mariadb"
    register: mariadb_pass_raw

  - name: Parse mariadb_pass
    set_fact:
      mariadb_pass: "{{ mariadb_pass_raw.stdout | b64decode }}"
      exporter_pass: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
      
  - name: print fact
    ansible.builtin.debug:
      msg:
      - "{{ exporter_pass }}"

  - name: Add helm repo
    kubernetes.core.helm_repository:
      name: prometheus-community
      repo_url: https://prometheus-community.github.io/helm-charts

  - name: Transfer values
    copy:
      src: "{{ role_path }}/files/grafana/values.yaml"
      dest: /home/k3s/grafana_values.yaml


  - name: Deploy Prometheus Operator with helm
    kubernetes.core.helm:
      name: prom-operator
      chart_ref: prometheus-community/kube-prometheus-stack
      update_repo_cache: true
      release_namespace: default
      values_files:
      -  /home/k3s/grafana_values.yaml

  - name: Delete old user if exists
    kubernetes.core.k8s_exec:
      namespace: default
      pod: cms-mariadb-0
      command: mariadb -uroot -p"{{ mariadb_pass }}" -e "DROP USER mysqld_exporter;"
    ignore_errors: true

  - name: Create user for mysql exporter
    kubernetes.core.k8s_exec:
      namespace: default
      pod: cms-mariadb-0
      command: mariadb -uroot -p"{{ mariadb_pass }}" -e "CREATE USER 'mysqld_exporter' IDENTIFIED BY '"{{ exporter_pass }}"' WITH MAX_USER_CONNECTIONS 3;"

  - name: Grant privileges for mysql exporter
    kubernetes.core.k8s_exec:
      namespace: default
      pod: cms-mariadb-0
      command: 
        mysql -uroot -p"{{ mariadb_pass }}" -e "GRANT PROCESS, REPLICATION CLIENT, REPLICATION SLAVE, SELECT ON *.* TO 'mysqld_exporter';"
        mysql -uroot -p"{{ mariadb_pass }}" -e "flush privileges;"

  - name: Deploy mysqld_exporter
    kubernetes.core.k8s:
      state: present
      namespace: default
      definition: "{{ lookup('template', 'mysqld_exporter.yaml.j2') | from_yaml }}"

  - name: Service for mysqld_exporter
    kubernetes.core.k8s:
      state: present
      namespace: default
      definition: "{{ lookup('file', 'mysqld_exporter_service.yaml') | from_yaml }}"
                
  - name: Create ServiceMonitor
    kubernetes.core.k8s:
      state: present
      namespace: default
      definition: "{{ lookup('file', 'ServiceMonitorMysql.yaml') | from_yaml }}"

  - name: Create ServiceMonitor for apache exporter
    kubernetes.core.k8s:
      state: present
      namespace: default
      definition: "{{ lookup('file', 'ServiceMonitorWordpress.yaml') | from_yaml }}"
    
  - name: Patch wordpress metric service
    kubernetes.core.k8s_json_patch:
      kind: Service
      namespace: default
      name: cms-wordpress-metrics
      patch:
        - op: add
          path: /metadata/labels/exporter
          value: apache
  - name: Load rules for database
    kubernetes.core.k8s:
      state: present
      namespace: default
      definition:
        apiVersion: monitoring.coreos.com/v1
        kind: PrometheusRule
        metadata:
          creationTimestamp: null
          labels:
            role: alert-rules
            release: prom-operator
          name: prometheus-mysql-rules
        spec:
          "{{ lookup('file', 'alerts/mysqld-exporter.yml') | from_yaml }}"

  - name: Load rules for apache
    kubernetes.core.k8s:
      state: present
      namespace: default
      definition:
        apiVersion: monitoring.coreos.com/v1
        kind: PrometheusRule
        metadata:
          creationTimestamp: null
          labels:
            role: alert-rules
            release: prom-operator
          name: prometheus-apache-rules
        spec:
          "{{ lookup('file', 'alerts/apache-exporter.yml') | from_yaml }}"
