---

  - name: Install pip if necessary
    package: name=python3-pip state=present

  - name: Install python deps
    pip:
      name: kubernetes

  - name: Install helm
    unarchive:
      src: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
      dest: /usr/local/bin
      extra_opts: "--strip-components=1"
      owner: root
      group: root
      mode: 0755
      remote_src: true
    args:
      creates: /usr/local/bin/helm

  - name: Init directory for some files
    file:
      path: /home/k3s
      state: directory
      mode: '0755'

  - name: Transfer values
    template:
      src: "{{ role_path }}/templates/wordpress/values.yaml.j2"
      dest: /home/k3s/wordpress-values.yaml 

  - name: Add certManager repo
    kubernetes.core.helm_repository:
      name: jetstack
      repo_url: https://charts.jetstack.io

  - name: Download certmanager CRDs
    get_url:
      url: "https://github.com/jetstack/cert-manager/releases/download/v{{ certmanagerCrd_version }}/cert-manager.crds.yaml"
      dest: /home/k3s/cert-manager.crds.yaml

  - name: Apply CertManager CRDs
    kubernetes.core.k8s:
      state: present
      src: /home/k3s/cert-manager.crds.yaml

  - name: Install CertManager with helm
    kubernetes.core.helm:
      name: "{{ certmanager_name }}"
      chart_ref: jetstack/cert-manager
      release_namespace: "{{ certmanager_namespace }}"
      create_namespace: true
      release_state: present

  - name: Create Issuer
    kubernetes.core.k8s:
      namespace: "{{ certmanager_namespace }}"
      definition: "{{ lookup('file', '{{ certmanager_issuer }}.yaml') | from_yaml_all }}"

  - name: Deploy Wordpress with helm
    kubernetes.core.helm:
      name: "{{ wordpress_name }}"
      chart_ref: oci://registry-1.docker.io/bitnamicharts/wordpress
      release_state: present
      release_namespace: "{{ wordpress_namespace }}"
      create_namespace: true
      values_files:
        -  /home/k3s/wordpress-values.yaml
