---

  - name: install pip if necessary
    when: os_type == "Ubuntu" 
    apt: name=python3-pip state=present

  - name: Install python deps
    pip:
      name: kubernetes

  - name: Install helm
    unarchive:
      src: https://get.helm.sh/helm-v3.11.0-linux-amd64.tar.gz
      dest: /usr/local/bin
      extra_opts: "--strip-components=1"
      owner: root
      group: root
      mode: 0755
      remote_src: true
    args:
      creates: /usr/local/bin/helm

  - name: Init directory for some files
    file:
      path: /home/k3s
      state: directory
      mode: '0755'

  - name: Transfer values
    template:
      src: "{{ role_path }}/templates/wordpress/values.yaml.j2"
      dest: /home/k3s/wordpress-values.yaml 

  - name: Add certManager repo
    kubernetes.core.helm_repository:
      name: jetstack
      repo_url: https://charts.jetstack.io

  - name: Download certmanager CRDs
    get_url:
      url: https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.crds.yaml
      dest: /home/k3s/cert-manager.crds.yaml

  - name: Apply CertManager CRDs
    kubernetes.core.k8s:
      state: present
      src: /home/k3s/cert-manager.crds.yaml

  - name: Install CertManager with helm
    kubernetes.core.helm:
      name: certmanager
      chart_ref: jetstack/cert-manager
      release_namespace: default
      release_state: present


  - name: Deploy Wordpress chart on 18.0.8 with values loaded from template
    kubernetes.core.helm:
      name: cms
      chart_ref: oci://registry-1.docker.io/bitnamicharts/wordpress
      chart_version: 18.0.8
      release_state: present
      release_namespace: default
      values_files:
        -  /home/k3s/wordpress-values.yaml
