apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-operator-apache-exporter
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/name: prometheus-apache-exporter
    jobLabel: apache-exporter
    release: prom-operator
spec:
  selector:
    matchLabels:
      exporter: apache
  endpoints:
  - interval: 5s
    targetPort: 9117
    path: /metrics
