---
k3s_version: v1.22.3+k3s1
ansible_user: root
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: >-
  --disable traefik
extra_agent_args: ""
ssh_users: ['k3s_operator']
ssh_port: '6733'
wordpress_domain: wordpress.karno.agitronic.net 
grafana_domain: grafana.karno.agitronic.net
alertmanager_domain: alertmanager.karno.agitronic.net
efk_kibanaDomain: kibana.karno.agitronic.net
certmanager_issuer: letsencrypt-prod
wordpress_name: cms
wordpress_namespace: default
